# Base Environment
FROM node:16.0.0-alpine

#Set the working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all other source code files
COPY . .

# ENV Variables

# Expose port
EXPOSE 8080

# Command to start the application
CMD ["npm", "run", "start"]